### ISSUE TITLE
Docs on k8s multi-namespace discovery 

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/helm-charts#371]
To get control to discover in multiple namespaces without the use of ClusterRole or ClusterRoleBindings:

- Update the deployment config for gm-control. The`gm_control_kubernetes_namespaces` env var should contain a comma-delimited string of namespaces.
- Apply the following roles. There should be 1 ServiceAccount in one of the namespaces (doesn't matter which), and then a pair of Role/RoleBinding definitions for each namespace.

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-sa
  namespace: ns-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-sa-rolebinding
  namespace: ns-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-sa-role
subjects:
  - kind: ServiceAccount
    name: control-sa
    namespace: ns-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-sa-rolebinding
  namespace: ns-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-sa-role
subjects:
  - kind: ServiceAccount
    name: control-sa
    namespace: ns-1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-sa-role
  namespace: ns-1
rules:
  - apiGroups: ['']
    resources: ['pods', 'endpoints']
    verbs: ['get', 'list', 'watch']
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-sa-role
  namespace: ns-2
rules:
  - apiGroups: ['']
    resources: ['pods', 'endpoints']
    verbs: ['get', 'list', 'watch']
```
