### ISSUE TITLE
data security contexts should be disabled for openshift

### ISSUE THREAD

**Issue by dgoldstein1** [DecipherNow/helm-charts#436]
## Description

The conditional 

```yaml
      {{- if .Values.data.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.data.securityContext.fsGroup }}
      {{- end }}
```

should also be evaluated for if environment != `openshift`

## Why is this a problem?

- containers in openshift will die immediatley if they are given a security context that doesn't exist
