### ISSUE TITLE
prometheus config should always scrape envoy metrics

### ISSUE THREAD

**Issue by justincely** [DecipherNow/helm-charts#543]
The current prom config only scrapes metrics if sense is enabled, and work only in special cases.  We can get past this, and turn on collection of envoy metrics for all sidecars, but changing the `prometheus.yaml` to the below:

```yaml
    global:
      scrape_interval:     5s
      evaluation_interval: 2m
    rule_files:
      - "/etc/prometheus/recording_rules.yaml"
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'gm-metrics'
        metrics_path: /prometheus
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - grey-matter
        relabel_configs:
        # Drop all named ports that are not "metrics"
        - source_labels: ['__meta_kubernetes_pod_container_port_name']
          regex: 'metrics'
          action: 'keep'
        # Relabel Jobs to the service name and version of the zk path
        - source_labels: ['__meta_kubernetes_pod_label_gmproxy']
          regex: '(.*)'
          target_label:  'job'
          replacement:   '${1}'
      - job_name: 'envoy-metrics'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - grey-matter
        relabel_configs:
        # Drop all named ports that are not "metrics"
        - source_labels: ['__meta_kubernetes_pod_container_port_name']
          regex: 'metrics'
          action: 'keep'
        # Relabel Jobs to the service name and version of the zk path
        - source_labels: ['__meta_kubernetes_pod_label_gmproxy']
          regex: '(.*)'
          target_label:  'job'
          replacement:   '${1}'
        - source_labels: ['__address__']
          regex: '(.*):(.*)'
          target_label:  '__address__'
          replacement:   '${1}:8001'

```
