### ISSUE TITLE
[release-2.2] Update globals.yaml to create a "control" map for configurables

### ISSUE THREAD

**Issue by chrisbsmith** [DecipherNow/helm-charts#586]
Now that there are multiple parameters for Control in the `globals.yaml` we should consider creating a map to consolidate these parameters.

**NOTE** this will be a cascading change and will require updates throughout the charts.

Currently:
```yaml
global:
  # Port for Grey Matter Control. Used in catalog init and sidecar envvars.
  control_port: 50000
  # The label Control will use to find pods to include in the mesh
  control_cluster_label: greymatter.io/control
```

Proposed:
```yaml
global:
  control:
    # Port for Grey Matter Control. Used in catalog init and sidecar envvars.
    port: 50000
    # The label Control will use to find pods to include in the mesh
    cluster_label: greymatter.io/control
```
