### ISSUE TITLE
[BUG] rds.enabled=true does not mean postgresql_endpoint is actually set 

### ISSUE THREAD

**Issue by moosecanswim** [DecipherNow/helm-charts#658]
This should allow the envar to be set but did not during a deployment.
```
      # Postgresql endpoint - only templated if rds is enabled, otherwise the var isn't included at all
      postgresql_endpoint:
        type: "{{- if .Values.postgres.rds.enabled }}value{{- else }}null{{- end }}"
        value: "{{ .Values.postgres.rds.endpoint }}"
```
