### ISSUE TITLE
Data aws configurations block

### ISSUE THREAD

**Issue by zoemccormick** [DecipherNow/helm-charts#722]
The pvc mount for internal-data is using the [default values](https://github.com/DecipherNow/helm-charts/blob/290561496837474c7778442eca343a9255d37ecd/data/gm-data/values.yaml#L174-L178) which are incorrect when internal data is not using s3.

We need to add this block to the data/values.yaml under data and internal-data for configuration clarity:

```yaml
  aws:
    access_key: xxx
    secret_key: xxx
    region: us-east-1
    bucket: decipher-quickstart-helm
```

and since uses3 if false by default, the default should probably be `bucket: local` instead
